---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# The Greater Toronto Area (GTA) R User Group

<!-- badges: start -->
<!-- badges: end -->

## What we're about

This group welcomes new and experienced R users to exchange knowledge and experience on using R for data analysis, data visualization, data reporting, or any other interesting use case. Information on upcoming and past meetings, such as location and time of our next meeting, can be found [on our Meetup page](https://www.meetup.com/Greater-Toronto-Area-GTA-R-Users-Group/).

This package can be obtained from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("gta-r-user-group/gtar")
```

## Code of Conduct

Please note that the 'gtar' project is released with a [Contributor Code of Conduct](CODE_OF_CONDUCT.md). By contributing to this project, you agree to abide by its terms.

## Materials

### 2019-09-10: GTA R Meetup

* [Shreejoy Tipathy](https://triplab.org/) talk: [Come for the machine learning, stay for the data science](https://github.com/gta-r-user-group/gtar/tree/master/2019-09-09/neuroinformatics_data_science.pdf)
* [Sharla Gelfand](https://twitter.com/sharlagelfand) Open Data Toronto:
    * [Demo](https://github.com/gta-r-user-group/gtar/tree/master/2019-09-09/opendatatoronto/opendatatoronto-demo.md)
    * [Toronto Open Data Portal](https://open.toronto.ca/)
    * [`opendatatoronto` R Package](https://sharlagelfand.github.io/opendatatoronto/)

### 2019-04-09: GTA R Meetup

* [Dean Attali](https://deanattali.com/) talk: [useR 2017 attendance Shiny app](https://daattali.com/shiny/user2017/) and [code on GitHub](https://github.com/daattali/user2017)
* [Morgan Taschuk](https://morgantaschuk.com/) talk: [Making research software more robust](https://docs.google.com/presentation/d/1cgFwOn37HDEzIqZIiCI1GVhVv9NS2HPcflp13vNQX0w/edit?usp=sharing) and [paper](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005412) 

### 2019-03-05: GTA RUG and R-Ladies Toronto Kickoff

* [`gt` materials](https://github.com/gta-r-user-group/gtar/tree/master/2019-03-05/rich-i)
* Opinionated Strategies for Uncharted Territories
    * [Materials](https://github.com/gta-r-user-group/gtar/tree/master/2019-03-05/opinionated-strategies-for-uncharted-territories)
    * [Slides](https://sharla.party/talks/rladies-rug-kickoff.html#1)
